# Impute PCA - Orange

In [1]:
import warnings
warnings.simplefilter(action='ignore', category=FutureWarning)
warnings.filterwarnings("ignore")

In [2]:
import pyreadr
result = pyreadr.read_r('./data/orange.rda')
orange = result["orange"]
orange

,Color.intensity,Odor.intensity,Attack.intensity,Sweet,Acid,Bitter,Pulp,Typicity
rownames,,,,,,,,
1,4.791667,5.291667,NaN,NaN,NaN,2.833333,NaN,5.208333
2,4.583333,6.041667,4.416667,5.458333,4.125000,3.541667,4.625000,4.458333
3,4.708333,5.333333,NaN,NaN,4.291667,3.166667,6.250000,5.166667
4,6.583333,6.000000,7.416667,4.166667,6.750000,NaN,1.416667,3.416667
5,NaN,6.166667,5.333333,4.083333,NaN,4.375000,3.416667,4.416667
6,6.333333,5.000000,5.375000,5.000000,5.500000,3.625000,4.208333,4.875000
7,4.291667,4.916667,5.291667,5.541667,5.250000,NaN,1.291667,4.333333
8,NaN,4.541667,4.833333,NaN,4.958333,2.916667,1.541667,3.958333
9,4.416667,NaN,5.166667,4.625000,5.041667,3.666667,1.541667,3.958333
10,4.541667,4.291667,NaN,5.791667,4.375000,NaN,NaN,5.000000
11,4.083333,5.125000,3.916667,NaN,NaN,NaN,7.333333,5.250000
12,6.500000,5.875000,6.125000,4.875000,5.291667,4.166667,1.500000,3.500000

In [3]:
from missmdatools import imputePCA
res_impute = imputePCA(X=orange,n_components=2)

0.11061657765389944

In [4]:
res_impute["completeObs"]

,Color.intensity,Odor.intensity,Attack.intensity,Sweet,Acid,Bitter,Pulp,Typicity
rownames,,,,,,,,
1,4.791667,5.291667,3.826375,5.584704,3.950442,2.833333,6.501759,5.208333
2,4.583333,6.041667,4.416667,5.458333,4.125000,3.541667,4.625000,4.458333
3,4.708333,5.333333,4.070594,5.460769,4.291667,3.166667,6.250000,5.166667
4,6.583333,6.000000,7.416667,4.166667,6.750000,4.806523,1.416667,3.416667
5,6.552292,6.166667,5.333333,4.083333,5.433866,4.375000,3.416667,4.416667
6,6.333333,5.000000,5.375000,5.000000,5.500000,3.625000,4.208333,4.875000
7,4.291667,4.916667,5.291667,5.541667,5.250000,3.193966,1.291667,4.333333
8,4.145741,4.541667,4.833333,5.572332,4.958333,2.916667,1.541667,3.958333
9,4.416667,5.058775,5.166667,4.625000,5.041667,3.666667,1.541667,3.958333
10,4.541667,4.291667,4.148464,5.791667,4.375000,2.678946,3.954459,5.000000
11,4.083333,5.125000,3.916667,5.752959,3.777752,2.748365,7.333333,5.250000
12,6.500000,5.875000,6.125000,4.875000,5.291667,4.166667,1.500000,3.500000